site_name: Indigo User Manual
nav:
    - Home: index.md
    - Installation: installation.md
    - Getting Started: getting-started.md
    - Constraints & Motivation: constraints-and-motivation.md
    - Prior Art: prior-art.md
    - Key Concepts: key-concepts.md
    - Configuration: configuration.md
    - Start Up: start-up.md
    - Entry Point Types: entry-point-types.md
    - Asset Management: asset-management.md
    - Logging: logging.md
    - Time & Temporal Values: time-and-temporal-values.md
    - Audio: audio.md
    - Networking: networking.md
    - Events & Signals: events-and-signals.md
    - Outcome: outcome.md
    - Collections, Abstractions & TypeClasses: collections-abstractions-and-typeclasses.md
    - Renderable Primitives: renderable-primitives.md
    - Primitive Types: primitive-types.md
    - SubSystems: subsystems.md
    - Scene Management: scene-management.md
    - UI Components: ui-components.md
    - Text & Fonts: text-and-fonts.md
    - Importers: importers.md
    - Animation: animation.md
theme: readthedocs
