- name: Scala Steward Github Action
  uses: scala-steward-org/scala-steward-action@v2.7.0

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.SCALA_STEWARD_INDIGO }}
